server:
  port: 8080
spring:
  datasource:
  #######################
  ###    谢岳宁的配置   ###
  #######################
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=false&useUnicode=yes&serverTimezone=UTC&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 56784321

  #######################
  ### 带刺的小老鼠的配置 ###
  #######################
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/library?useSSL=false&useUnicode=yes&serverTimezone=UTC&autoReconnect=true&characterEncoding=utf8
#  username: root
#  password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
