spring:
  profiles:
    active: dev
#    active: prod

# 解决springboot与swagger不匹配的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

##yml整合mybatis（暂时不需要）
#mybatis:
#  type-aliases-package : com.example.librarymap.pojo
#  mapperLocations: classpath:mapper/*.xml

#server:
#  ssl:
#    key-store: classpath:www.jumboxtech.com.jks
#    key-store-password: zgg00o7b7xd8cj
#    key-store-type: JKS
